---
  - name: Install pip
    become: true
    package:
      name: "python3-pip"
      state: latest

  - name: Install docker library
    become: true
    pip:
      name: "docker"
      state: latest

  - name: Run a container
    become: true
    docker_container:
      name: app_python
      image: "{{ image }}"
      state: started
      ports:
        - "5000:5000"

  # Acknowledgements:
  # https://docs.ansible.com/ansible/2.5/modules/docker_container_module.html#examples
