apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "time-app.fullname" . }}
  labels:
    {{- include "time-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.serviceName }}
  podManagementPolicy: Parallel
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "time-app.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128M
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "time-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "time-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: example-config
        - name: init-example
          emptyDir: {}
      initContainers:
        - name: init-example
          image: busybox
          command:
            - wget
            - "-O"
            - "/init-example/example.com.html"
            - "https://example.com/"
          volumeMounts:
            - name: init-example
              mountPath: /init-example
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: files/config.yaml
            - name: logs
              mountPath: /app/logs
            - name: init-example
              mountPath: /init-example
          env:
            - name: super-secret
              valueFrom:
                secretKeyRef:
                  name: super-secret
                  key: secret_key
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
