---
  - name: Set the stable docker repository
    # taken from https://superuser.com/a/1326644/1224556
    apt_repository: 
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
      state: present
      update_cache: yes
  - name: Install docker
    become: true
    apt:
      name: docker-ce
      state: present